add tooltip to indicator
elementary/wingpanel-indicator-nightlight pull request #75
Opened 2020-12-03 02:29 UTC by andirsun

2020-12-10 21:54 UTC, andirsun commented
## Demo : 
### Enable case : 
![on](https://user-images.githubusercontent.com/22928302/101834378-48145000-3b08-11eb-87d0-ef129f42ad8b.png)
### Snozed case : 
![Screenshot from 2020-12-10 16-52-00](https://user-images.githubusercontent.com/22928302/101834407-52cee500-3b08-11eb-92b1-07785b944058.png)

2020-12-10 22:23 UTC, cassidyjames requested changes
As we landed in https://github.com/elementary/wingpanel-indicator-keyboard/pull/87, I think the copy here should be,

>Night Light is on

and

>Night Light is off

I suspect the way the markup string is being constructed is also not the most translatable; perhaps it would be better to just have a separate string for each case, like you have with the `accel` string?

2020-12-10 22:24 UTC, cassidyjames commented
Something else I'm wondering: should we be handling this markup with a Granite utility to keep its styling in-line with the accel tooltips? It feels bad to be carrying the styling in both Granite and here to match. Thoughts from @elementary/desktop-developers?

2020-12-10 22:30 UTC, andirsun commented
> Something else I'm wondering: should we be handling this markup with a Granite utility to keep its styling in-line with the accel tooltips? It feels bad to be carrying the styling in both Granite and here to match. Thoughts from @elementary/desktop-developers?

I have tried 
```
Granite.markup_accel_tooltip ({"<small>Middle-click to snooze</small>"}, _("example"));
```
But the accel doesnt show, I think this is a bug with granite

2020-12-11 04:01 UTC, cassidyjames commented
@andirsun no, Granite is working correctly; it is intended to pass keycodes to the accel tooltip, not a string. What I am wondering is if we should have a new utility that does accept a freeform string, like `Granite.markup_tooltip_with_s ()` or something maybe less-terribly named. :smile:

2020-12-11 12:06 UTC, andirsun commented
@cassidyjames  Oh I got the idea!, 
Should I work on that change in granite before implementing this ?

2020-12-15 19:38 UTC, cassidyjames commented on src/Indicator.vala
> +    }
I think this translates my comments into code:

```suggestion
        string primary_text = _("Night Light is on");
        string secondary_text = _("Middle-click to snooze");

        if (status) {
            primary_text = _("Night Light is snoozed");
            secondary_text = _("Middle-click to enable");
        }

        indicator_icon.tooltip_markup = "%s\n%s".printf (
            primary_text,
            Granite.TOOLTIP_SECONDARY_TEXT_MARKUP.printf (secondary_text)
        );
    }
```

I am a little confused by `status` though; it seems backwards to me? If status is true, I would think Night Light would be on. Perhaps a more clear variable name is warranted.

2020-12-15 20:59 UTC, cassidyjames requested changes
I think we can change `status` to `snoozed` to be more clear. I think I hit all the instances, but it would be good to double-check.

2020-12-15 20:59 UTC, cassidyjames commented on src/Indicator.vala
> +    private bool nightlight_status;
```suggestion
    private bool snoozed;
```

2020-12-15 20:59 UTC, cassidyjames commented on src/Indicator.vala
> +        nightlight_status = false;
```suggestion
        snoozed = false;
```

2020-12-15 20:59 UTC, cassidyjames commented on src/Indicator.vala
> +            update_tooltip (nightlight_status);
```suggestion
            update_tooltip (snoozed);
```

2020-12-15 20:59 UTC, cassidyjames commented on src/Indicator.vala
> +    private void update_tooltip (bool status) {
```suggestion
    private void update_tooltip (bool snoozed) {
```

2020-12-15 20:59 UTC, cassidyjames commented on src/Indicator.vala
> +        if (status) {
```suggestion
        if (snoozed) {
```

2020-12-15 21:29 UTC, cassidyjames approved these changes
Huzzah!

2020-12-15 21:54 UTC, danrabbit reviewed
Hrm, quick question inline

2020-12-15 21:54 UTC, danrabbit commented on src/Indicator.vala
> +            update_tooltip (snoozed);
Hold the phone a second. Is this value ever anything other than `false` and is it ever different from `nightlight_manager.snoozed`? Should this be
```suggestion
            update_tooltip (nightlight_manager.snoozed);
```

2020-12-15 22:00 UTC, andirsun commented on src/Indicator.vala
> +            update_tooltip (snoozed);
@danrabbit  Yep, it works too! Thanks for code review

2020-12-21 18:17 UTC, danrabbit commented
Looks good, nice work!

2020-12-21 18:17 UTC, merged